// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2RvF5IO_j6lkIey-_FbYhPZY29keXOhg',
    appId: '1:76883414918:web:f271faf41083010c1aa607',
    messagingSenderId: '76883414918',
    projectId: 'spoco-app-e3ab6',
    authDomain: 'spoco-app-e3ab6.firebaseapp.com',
    storageBucket: 'spoco-app-e3ab6.appspot.com',
    measurementId: 'G-BBRRDGZC7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5uzqIUZTK7mU1Bi46Oe8TnGa1VzDXfzw',
    appId: '1:76883414918:android:32cfa0fd1cc08c311aa607',
    messagingSenderId: '76883414918',
    projectId: 'spoco-app-e3ab6',
    storageBucket: 'spoco-app-e3ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7g67m9W0VQOe-MXUmRa_kTJQr5t3kZU8',
    appId: '1:76883414918:ios:8ab0680cf0fd4a381aa607',
    messagingSenderId: '76883414918',
    projectId: 'spoco-app-e3ab6',
    storageBucket: 'spoco-app-e3ab6.appspot.com',
    iosBundleId: 'com.example.spocoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7g67m9W0VQOe-MXUmRa_kTJQr5t3kZU8',
    appId: '1:76883414918:ios:8ab0680cf0fd4a381aa607',
    messagingSenderId: '76883414918',
    projectId: 'spoco-app-e3ab6',
    storageBucket: 'spoco-app-e3ab6.appspot.com',
    iosBundleId: 'com.example.spocoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2RvF5IO_j6lkIey-_FbYhPZY29keXOhg',
    appId: '1:76883414918:web:3372c371e26777ea1aa607',
    messagingSenderId: '76883414918',
    projectId: 'spoco-app-e3ab6',
    authDomain: 'spoco-app-e3ab6.firebaseapp.com',
    storageBucket: 'spoco-app-e3ab6.appspot.com',
    measurementId: 'G-82R6WYX3QQ',
  );

}